services:
  web:
    build:
      context: .
      dockerfile: service/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URI=postgresql://postgres:postgres@db:5432/postgres
      - ENV=development
      - TESTING=False
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
