apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts-service
  labels:
    app: accounts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accounts
  template:
    metadata:
      labels:
        app: accounts
    spec:
       containers:
        - name: accounts-service
          image: image-registry.openshift-image-registry.svc:5000/sn-labs-nicolegonzal/accounts-service
          command: ["gunicorn"]
          args: ["--bind", "0.0.0.0:5000", "service.app:app"]
---
apiVersion: v1
kind: Service
metadata:
  name: accounts-service
spec:
  type: ClusterIP
  selector:
    app: accounts
  ports:
  - port: 5000
    targetPort: 5000
