name: CI Build  # El nombre que definimos

on:
  push:
    branches: [ "main" ]  # Se dispara en cada push a main
  pull_request:
    branches: [ "main" ]  # Se dispara en cada pull request a main

jobs:
  build:  # El nombre del job que configuramos
    runs-on: ubuntu-latest  # <--- AQUÍ VA LA LÍNEA

    container:
        image: python:3.11-slim

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Run tests
        run: nosetests -v
